# part of this code was generated by ChatGPT in December 2024

rm(list=ls())

###################
################### LOAD LIBRARIES AND DATA
###################

library(ggplot2)
library(dplyr)
library(binsreg)

data(iris)

###################
################### BINSCATTER USING BINSREG PACKAGE
###################

binsreg(data=iris, 
      y=Petal.Length, 
      x=Sepal.Length)

###################
################### BINSCATTER FROM SCRATCH
###################

bins <- 10

iris_binned <- iris %>%
  mutate(bin = cut(Sepal.Length, breaks = bins, include.lowest = TRUE)) %>%
  group_by(bin) %>%
  summarize(
    bin_mid = mean(as.numeric(gsub("\\[|\\]|\\(|\\)", "", strsplit(as.character(bin), ",")[[1]]))),  # Extract midpoint
    mean_petal_length = mean(Petal.Length)
  ) %>%
  ungroup()
head(iris_binned)

ggplot(iris_binned, aes(x = bin_mid, y = mean_petal_length)) +
  geom_point() +
  labs(
    title = "Binscatter: Sepal Length vs Petal Length",
    x = "Binned Sepal Length",
    y = "Mean Petal Length"
  )
